---
# Source: splunk-otel-collector/templates/revert-patch-log-dirs-hook.yaml
apiVersion: v1
kind: Pod
metadata:
  name: default-splunk-otel-collector-revert-patch-log-dir
  labels:
    app.kubernetes.io/name: splunk-otel-collector
    helm.sh/chart: splunk-otel-collector-0.70.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: default
    app.kubernetes.io/version: "0.70.0"
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  restartPolicy: Never
  containers:
  - name: revert-patch-log-dirs
    image: registry.access.redhat.com/ubi9/ubi
    imagePullPolicy: IfNotPresent
    securityContext:
      runAsUser: 0
    command: ['sh', '-c', '
    setfacl --recursive --remove-all  /var/addon/splunk/otel_pos;
    setfacl --recursive --remove-all  /var/log;
    if [ -d "/var/lib/docker/containers" ];
    then
        setfacl --recursive --remove-all  /var/lib/docker/containers;
    fi;
    if [ -d "/var/log/crio/pods" ];
    then
        setfacl --recursive --remove-all  /var/log/crio/pods;
    fi;
    if [ -d "/var/log/pods" ];
    then
        setfacl --recursive --remove-all  /var/log/pods;
    fi;
    if [ -d "/var/addon/splunk/persist/agent" ];
    then
      setfacl --recursive --remove-all /var/addon/splunk/persist/agent;
    fi;
    if [ -d "/var/addon/splunk/persist/gateway" ];
    then
      setfacl --recursive --remove-all /var/addon/splunk/persist/gateway;
    fi;
    if [ -d "/var/addon/splunk/persist/clusterReceiver" ];
    then
      setfacl --recursive --remove-all /var/addon/splunk/persist/clusterReceiver;
    fi;']
    volumeMounts:
      - name: checkpoint
        mountPath: /var/addon/splunk/otel_pos
      - name: fluentd-checkpoint-dir
        mountPath: /var/log
      - name: varlog-crio-pods
        mountPath: /var/log/crio/pods
      - name: varlog-pods
        mountPath: /var/log/pods
      - name: varlibdockercontainers
        mountPath: /var/lib/docker/containers
      - name: persistent-queue-agent
        mountPath: /var/addon/splunk/persist/agent
      - name: persistent-queue-cluster-receiver
        mountPath: /var/addon/splunk/persist/clusterReceiver
  volumes:
    - name: checkpoint
      hostPath:
        path: /var/addon/splunk/otel_pos
    - name: varlog-crio-pods
      hostPath:
        path: /var/log/crio/pods
    - name: varlog-pods
      hostPath:
        path: /var/log/pods
    - name: varlibdockercontainers
      hostPath:
        path: /var/lib/docker/containers
    - name: fluentd-checkpoint-dir
      hostPath:
        path: /var/log
        type: DirectoryOrCreate
    - name: persistent-queue-agent
      hostPath:
          path: /var/addon/splunk/persist/agent
          type: DirectoryOrCreate
    - name: persistent-queue-cluster-receiver
      hostPath:
          path: /var/addon/splunk/persist/clusterReceiver
          type: DirectoryOrCreate
