{{ if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "splunk-otel-collector.fullname" . }}
  labels:
    {{- include "splunk-otel-collector.commonLabels" . | nindent 4 }}
    app: {{ template "splunk-otel-collector.name" . }}
    chart: {{ template "splunk-otel-collector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
{{- $groupedObjects := fromYaml (include "splunk-otel-collector.clusterReceiver.rules" . ) }}
{{- if $groupedObjects }}
{{- range $apiGroup, $resources := $groupedObjects }}
{{- if $resources }}
- apiGroups:
  - {{ $apiGroup }}
  resources:
  {{- range $resources }}
  - {{ . }}
  {{- end }}
  verbs:
  - get
  - list
  - watch
{{- end }}
{{- end }}
{{- end }}
{{- if eq (include "splunk-otel-collector.distribution" .) "openshift" }}
- apiGroups:
  - quota.openshift.io
  resources:
  - clusterresourcequotas
  verbs:
  - get
  - list
  - watch
{{- end }}
- apiGroups:
  - ""
  resources:
  - events
  - namespaces
  - namespaces/status
  - nodes
  - nodes/spec
  - nodes/stats
  - nodes/proxy
  - pods
  - pods/status
  - persistentvolumeclaims
  - persistentvolumes
  - replicationcontrollers
  - replicationcontrollers/status
  - resourcequotas
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - daemonsets
  - deployments
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
    - autoscaling
  resources:
    - horizontalpodautoscalers
  verbs:
    - get
    - list
    - watch
- nonResourceURLs:
  - /metrics
  verbs:
  - get
  - list
  - watch
{{- if eq (include "splunk-otel-collector.distribution" .) "eks/fargate" }}
- apiGroups:
    - ""
  resources:
    - nodes
  verbs:
    - patch
{{- end }}
{{- with .Values.rbac.customRules }}
{{ toYaml . }}
{{- end }}
{{- end }}
