{{ if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "splunk-otel-collector.fullname" . }}
  labels:
    {{- include "splunk-otel-collector.commonLabels" . | nindent 4 }}
    app: {{ template "splunk-otel-collector.name" . }}
    chart: {{ template "splunk-otel-collector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
{{- include "splunk-otel-collector.clusterRole.rules" . }}
- nonResourceURLs:
  - /metrics
  verbs:
  - get
  - list
  - watch
{{- if eq (include "splunk-otel-collector.distribution" .) "eks/fargate" }}
- apiGroups:
    - ""
  resources:
    - nodes
  verbs:
    - patch
{{- end }}
{{- with .Values.rbac.customRules }}
{{ toYaml . }}
{{- end }}
{{- end }}
