{{- if and .Values.networkExplorer.enabled .Values.networkExplorer.cloudCollector.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.networkExplorer.cloudCollector.serviceAccount.iamRole }}
  labels:
    app: {{ include "splunk-otel-collector-cloud-collector.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ include "splunk-otel-collector-cloud-collector.serviceAccountName" . }}
{{- end -}}
