{{- if .Values.networkExplorer.enabled}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "splunk-otel-collector.fullname" . }}-config
  namespace: {{ .Release.Namespace | quote }}
data:
  config.yaml: |
    labels:
      environment: {{ .Values.clusterName }}
{{- end }}
