{{- if and .Values.networkExplorer.enabled .Values.networkExplorer.kernelCollector.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ include "splunk-otel-collector-kernel-collector.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ include "splunk-otel-collector-kernel-collector.serviceAccountName" . }}
{{- end -}}
