{{- if .Values.networkExplorer.enabled}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "splunk-otel-collector-reducer.fullname" . }}
  labels:
    helm.sh/chart: {{ include "splunk-otel-collector.chart" . }}
    app.kubernetes.io/name: {{ include "splunk-otel-collector-reducer.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "splunk-otel-collector-reducer.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: telemetry
      port: {{ .Values.networkExplorer.reducer.telemetryPort }}
      targetPort: telemetry
      protocol: TCP
    {{- if not .Values.networkExplorer.reducer.disableInternalMetrics }}
    - name: stats
      port: {{ .Values.networkExplorer.reducer.statsPromPort }}
      targetPort: stats
      protocol: TCP
    {{- end }}
{{- end }}
