# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
change_type: enhancement
# The name of the component, or a single word describing the area of concern, (e.g. agent, clusterReceiver, gateway, networkExplorer, operator, chart, other)
component: agent, fluentd
# A brief description of the change. Surround your text with quotes ("") if it needs to start with a backtick (`).
note: Allow users to override `enable_stat_watcher` and `refresh_interval` for tail plugin from values.yaml
# One or more tracking issues related to the change
issues: [982]
# (Optional) One or more lines of additional information to render under the primary note.
# These lines will be padded with 2 spaces and then inserted directly into the document.
# Use pipe (|) for multiline entries.
subtext:
